[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube

build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32F103xB
    -Iinclude

board_build.ldscript = STM32F103C8TX_FLASH.ld

upload_protocol = stlink
monitor_speed = 115200
